import { useState, useEffect } from 'react';

interface Citation {
  index: number;
  document_id: string;
  filename: string;
  page: number;
  storage_url: string;
}

interface Alert {
  title: string;
  summary: string;
  equipment_affected: string[];
  recommendation: string;
  citations: Citation[];
}

interface AttritionRisk {
  equipment_id: string;
  equipment_name: string;
  doc_count: number;
  tacit_note_count: number;
  risk_score: number;
  risk_level: 'High' | 'Medium' | 'Low';
}

export default function Lessons() {
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [attritionRisk, setAttritionRisk] = useState<AttritionRisk[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetchFeed();
  }, []);

  const fetchFeed = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch('/agents/lessons/feed');
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      setAlerts(data.alerts || []);
      setAttritionRisk(data.attrition_risk || []);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Failed to fetch lessons learned feed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex-1 flex flex-col h-full bg-surface-container-lowest overflow-hidden">
      <div className="p-8 border-b border-outline-variant bg-white flex-shrink-0 flex items-center justify-between">
        <div>
          <h1 className="text-headline-lg font-headline-lg text-on-surface flex items-center gap-3">
            <span className="material-symbols-outlined text-primary text-4xl" style={{ fontVariationSettings: "'FILL' 1" }}>tips_and_updates</span>
            Lessons Learned & Failure Intelligence
          </h1>
          <p className="text-body-md text-on-surface-variant mt-2 max-w-2xl">
            Proactive alerts generated by scanning incident and failure records across the entire knowledge base for recurring patterns.
          </p>
        </div>
        <button 
          onClick={fetchFeed}
          disabled={loading}
          className="px-4 py-2 flex items-center gap-2 bg-surface-container hover:bg-surface-container-high rounded-md transition-colors text-label-md font-label-md text-on-surface"
        >
          <span className={`material-symbols-outlined text-lg ${loading ? 'animate-spin' : ''}`}>
            sync
          </span>
          Refresh Feed
        </button>
      </div>

      <div className="flex-1 overflow-y-auto custom-scrollbar p-8">
        <div className="max-w-4xl mx-auto space-y-6">
          {loading ? (
            <div className="flex flex-col items-center justify-center py-20 gap-4">
              <span className="material-symbols-outlined text-primary text-5xl animate-spin">progress_activity</span>
              <p className="text-headline-md font-headline-md text-on-surface">Analyzing Maintenance Records...</p>
              <p className="text-body-md text-on-surface-variant">Detecting cross-equipment failure patterns</p>
            </div>
          ) : error ? (
            <div className="flex flex-col items-center justify-center py-20 gap-3">
              <span className="material-symbols-outlined text-red-500 text-5xl">error</span>
              <p className="text-body-md text-red-700">{error}</p>
            </div>
          ) : (
            <>
              {/* Attrition Risk Section */}
              {attritionRisk.length > 0 && (
                <div className="bg-white border border-outline-variant rounded-xl shadow-sm p-6 mb-8">
                  <h2 className="text-headline-sm font-headline-sm text-on-surface mb-2 flex items-center gap-2">
                    <span className="material-symbols-outlined text-red-500">warning</span>
                    Knowledge Attrition Risk
                  </h2>
                  <p className="text-body-md text-on-surface-variant mb-4">
                    Equipment highly documented formally, but lacking captured tacit field insights. High risk if SMEs retire.
                  </p>
                  <div className="space-y-3">
                    {attritionRisk.map((risk, i) => (
                      <div key={i} className="flex justify-between items-center p-3 bg-surface-container-low rounded-lg">
                        <div>
                          <p className="font-semibold text-on-surface">{risk.equipment_name}</p>
                          <p className="text-sm text-on-surface-variant">Docs: {risk.doc_count} | Tacit Notes: {risk.tacit_note_count}</p>
                        </div>
                        <div className="flex items-center gap-3">
                          <span className={`px-2 py-1 rounded text-xs font-bold ${
                            risk.risk_level === 'High' ? 'bg-red-100 text-red-700' :
                            risk.risk_level === 'Medium' ? 'bg-orange-100 text-orange-700' :
                            'bg-green-100 text-green-700'
                          }`}>
                            {risk.risk_level} Risk ({risk.risk_score})
                          </span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {alerts.length === 0 ? (
                <div className="flex flex-col items-center justify-center py-20 gap-4 bg-white border border-outline-variant rounded-xl shadow-sm">
                  <span className="material-symbols-outlined text-primary text-5xl">check_circle</span>
                  <h2 className="text-headline-md font-headline-md text-on-surface">No Patterns Detected</h2>
                  <p className="text-body-md text-on-surface-variant text-center max-w-md">
                    The AI scanned all approved work orders and incident records but did not find any recurring failure patterns matching the threshold.
                  </p>
                </div>
              ) : (
                alerts.map((alert, index) => (
              <div key={index} className="bg-white border border-outline-variant rounded-xl shadow-sm overflow-hidden flex flex-col md:flex-row relative">
                {/* Visual indicator bar */}
                <div className="w-full md:w-1.5 bg-orange-400 flex-shrink-0"></div>
                
                <div className="p-6 flex-1 flex flex-col">
                  <div className="flex items-start gap-4 mb-4">
                    <div className="bg-orange-100 text-orange-700 p-3 rounded-full flex-shrink-0">
                      <span className="material-symbols-outlined text-2xl">trending_up</span>
                    </div>
                    <div className="flex-1">
                      <h2 className="text-headline-sm font-headline-sm text-on-surface leading-tight">
                        {alert.title}
                      </h2>
                      <div className="flex items-center gap-2 mt-2 flex-wrap">
                        <span className="px-2 py-0.5 bg-surface-container text-on-surface-variant text-label-sm rounded border border-outline-variant flex items-center gap-1">
                          <span className="material-symbols-outlined text-[14px]">precision_manufacturing</span>
                          Affected: {alert.equipment_affected.join(', ')}
                        </span>
                      </div>
                    </div>
                  </div>
                  
                  <div className="space-y-4">
                    <div>
                      <h3 className="text-label-md font-label-md text-on-surface-variant uppercase tracking-wider mb-1">Pattern Summary</h3>
                      <p className="text-body-md text-on-surface leading-relaxed">
                        {alert.summary}
                      </p>
                    </div>
                    
                    <div className="bg-lime-50 border border-lime-100 rounded-lg p-4 flex items-start gap-3">
                      <span className="material-symbols-outlined text-lime-600 mt-0.5">lightbulb</span>
                      <div>
                        <h3 className="text-label-md font-label-md text-lime-900 mb-1">Recommendation</h3>
                        <p className="text-body-md text-lime-800">
                          {alert.recommendation}
                        </p>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Right side citations panel */}
                {alert.citations && alert.citations.length > 0 && (
                  <div className="bg-surface-container-lowest border-t md:border-t-0 md:border-l border-outline-variant p-6 w-full md:w-72 flex-shrink-0">
                    <h3 className="text-label-md font-label-md text-on-surface-variant flex items-center gap-2 mb-4">
                      <span className="material-symbols-outlined text-[18px]">library_books</span>
                      Supporting Records
                    </h3>
                    <div className="space-y-3">
                      {alert.citations.map((c, i) => (
                        <a
                          key={i}
                          href={`${c.storage_url}#page=${c.page}`}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="flex items-start gap-3 p-3 bg-white border border-outline-variant rounded-lg hover:border-primary transition-all group"
                        >
                          <div className="bg-red-50 text-red-600 p-1.5 rounded flex-shrink-0">
                            <span className="material-symbols-outlined text-[18px]">picture_as_pdf</span>
                          </div>
                          <div className="flex-1 min-w-0">
                            <p className="text-label-sm text-on-surface font-medium truncate" title={c.filename}>
                              {c.filename}
                            </p>
                            <p className="text-[11px] text-on-surface-variant mt-0.5">
                              Citation [{c.index}] • Page {c.page}
                            </p>
                          </div>
                        </a>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            ))
          )}
          </>
          )}
        </div>
      </div>
    </div>
  );
}
